### ISSUE TITLE
Nomadhys télécharge le fichier mais ne semble pas arriver à importer les données

### ISSUE THREAD

**Issue by Yvan-Masson** [Noethys/Nomadhys#2]
Bonjour,

Merci encore pour ce beau logiciel.

À la mise en service d'une tablette avec Nomadhys, identique à une autre qui marche parfaitement, le téléchargement des données via Wi-Fi se passe bien (on le voit également sur Noethys) :
```
…
Transfert réussi
Décryptage du fichier
```

Par contre, en bas à gauche de l'écran d'accueil le message suivant reste :
```
IDfichier saisi
Synchronisez maintenant pour recevoir la base
```
Par conséquent il n'est pas possible d'accéder aux Individus ni aux Consommations. J'ai vérifié plusieurs fois le mot de passe de chiffrement du fichier. J'ai déjà essayé sans succès de supprimer le cache de l'application, les données de l'application et de réinstaller l'application.

Je suis preneur de toute suggestion :-)

Merci d'avance,
Yvan

**Comment by Noethys** [comment]
Bonjour,

Difficile à dire...
Il n'y a pas d'erreur dans le IDfichier saisi ?

Ivan

**Comment by Yvan-Masson** [comment]
Merci pour la réponse rapide. Non, j'ai refait la configuration au moins 3 fois, toujours avec le même résultat (le fichier est bien téléchargé mais on dirait qu'il n'en fait rien).

**Comment by Noethys** [comment]
C'est bien mystérieux. Je ne vois qu'une possibilité : consulter le log. Mais c'est assez technique : 

1. Télécharger l'outil ADB : https://dl.google.com/android/repository/platform-tools-latest-windows.zip
2. Activer le mode "développeur" de la tablette : https://www.frandroid.com/comment-faire/tutoriaux/184906_comment-acceder-au-mode-developpeur-sur-android
3. Brancher la tablette au PC.
4. Ouvrir une console "Invite de commandes", se place dans le répertoire où est ADB.
5. Lancer la commande : `adb logcat -s "python"`
6. Faire la commande "Recevoir les données" dans Nomadhys et regarder le log apparaître en temps réel.

IL faudrait m'envoyer ce log.

**Comment by Yvan-Masson** [comment]
Ok, je me doutais qu'il faudrait peut-être en passer par là, mais avec vos indications ça devrait aller :-) Je fais ça dès que possible.

**Comment by Yvan-Masson** [comment]
Désolé pour le temps de latence. Le fichiers de log est là : [nomadhys-log.txt](https://github.com/Noethys/Nomadhys/files/5608399/nomadhys-log.txt)

**Comment by Noethys** [comment]
Bonjour,

Je ne vois pas d'où peut venir ce problème, d'autant que cela semble fonctionner ailleurs. Il faudrait essayer ceci : 

1. Télécharger la dernière version beta de Noethys depuis le site (Rubrique Téléchargements > Version Beta).
2. Installer et ouvrir Noethys.
3. Aller dans Menu Outils > Utilitaires admin > Ouvrir le répertoire Utilisateur.
4. Ouvrir le fichier Customize.ini qui apparaît dans le répertoire.
5. Ajouter ceci quelque part dans le fichier : 
```
[version_cryptage]
nomadhys = 2
```
6. Enregistrer le fichier.
7. Relancer Noethys.

**Comment by Yvan-Masson** [comment]
Bonjour,

Je viens de faire le test avec Noethys 1.2.8.4 et effectivement ça marche. Si jamais ça vous intéresse, le log de la tablette est ici : 
[Nomadhys-avec-Noethys-beta.txt](https://github.com/Noethys/Nomadhys/files/5616785/Nomadhys-avec-Noethys-beta.txt)

**Comment by Noethys** [comment]
Ah, bonne nouvelle !
